name: docker-branch

on:
  push:
    branches-ignore:
    - 'master'
    tags-ignore:
    - 'v*'

jobs:
  docker_build_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: stjude/xenocp
        tags: branch-${GITHUB_REF##*/}
