name: docker-master

on:
  push:
    branches:
    - 'master'

jobs:
  docker_build_master:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: stjude/xenocp
        tag_with_ref: true 
